---
title: "Spatial Analysis (Interactive)"
author: "Bernard Kilonzo"
format: html
code-fold: true
code-summary: "show the code"
editor: visual
---

## Sample Size by Commune (Haiti)

```{r}
#| label: load-libraries
#| include: true
#| message: false
#| warning: false

#loading libraries
library(tidyverse)
library(sf)
library(paletteer)

#loading data
setwd("C:\\Users\\berna\\OneDrive\\Desktop\\Production\\dataviz\\code\\Map\\haiti_adm2_boundaries")
survey_sample<-read.csv("https://raw.githubusercontent.com/bernardkilonzo-rigor/dataviz/refs/heads/main/data/Survey%20Sample.csv")
adm2_shapefiles<-st_read("hti_boundaries_communes_adm2_cnigs_polygon.shp", quiet = TRUE)

#joining data sets
merged_data<-adm2_shapefiles%>%left_join(
  survey_sample, by =c("commune"="Commune"))

#creating a map
merged_data%>%ggplot(aes(geometry=geometry, label = commune,
                         fill = Sample.Size))+
  geom_sf(color ="white", linewidth = 0.1)+
  scale_fill_gradient(low = "#fe9f6d", high = "#3b0f70")+
  labs(title = "Survey Sample Size by Commune in Haiti",
       caption = "Viz By: Bernard Kilonzo",
       fill = "Sample Size")+
  theme(panel.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(family = "serif", face = "bold",size = 12),
        plot.subtitle = element_text(family = "serif", size = 10,face = "italic" ,color = "gray22"),
        plot.caption = element_text(family = "serif",  size = 8),
        legend.title = element_text(family = "serif", size = 8),
        legend.text = element_text(family = "serif", size = 8))

```

## Sample Size by Commune Haiti (Interactive)

```{r}
#| label: load-libraries
#| include: true
#| message: false
#| warning: false

#loading libraries
library(tidyverse)
library(sf)
library(paletteer)
library(leaflet)

#loading data
setwd("C:\\Users\\berna\\OneDrive\\Desktop\\Production\\dataviz\\code\\Map\\haiti_adm2_boundaries")
survey_sample<-read.csv("https://raw.githubusercontent.com/bernardkilonzo-rigor/dataviz/refs/heads/main/data/Survey%20Sample.csv")
adm2_shapefiles<-st_read("hti_boundaries_communes_adm2_cnigs_polygon.shp", quiet = TRUE)

#joining data sets
merged_data<-adm2_shapefiles%>%left_join(
  survey_sample, by =c("commune"="Commune"))

#creating color palette
Pal <- colorNumeric(
  palette = as.character(paletteer::paletteer_d("MoMAColors::Alkalay2")),
  domain = merged_data$Sample.Size
)

#creating an interactive map
leaflet(merged_data)%>%
  addTiles()%>%
  addPolygons(
    fillColor = ~Pal(Sample.Size),
    fillOpacity = 0.8,
    color = "white",
    weight = 1
  )
```
